### ISSUE TITLE
Prop vs. bool (in eq_nat)

### ISSUE THREAD

**Issue by sophiechoi** [snu-sf/pl2015#52]
#### Problem

I tried to execute this Fixpoint called "eq_nat" in Basics.v
and wanted to get a "true" or a "false" as a return value.
But instead, I got a "True" or a "False", and failed to get a "bool".

```
Fixpoint eq_nat n m: Prop :=
    match n, m with
    | O, O => True
    | O, S => False
    | S _, O => False
    | S n1, S m1 => eq_nat n1 m1
    end.
```
#### Solution

To solve this problem changed 
Prop, True, False to bool, true, false
in Fixpoint eq_nat.

and then I could get a "bool."

```
Fixpoint eq_nat n m: bool :=
    match n, m with
    | O, O => true
    | O, S => false
    | S _, O => false
    | S n1, S m1 => eq_nat n1 m1
    end.
```

**Comment by jeehoonkang** [comment]
@sophiechoi Thank you for giving us a decent tip!

**Comment by jaewooklee93** [comment]
If you want to get `bool`, you can use `beq_nat`, too.

**Comment by jeehoonkang** [comment]
@jaewooklee93 Thank you for your keen observation. Using already-defined things is always good!

Jeehoon

**Comment by sophiechoi** [comment]
@jaewooklee93 Thank you for reply! 

At first, I misunderstood the Prop one with the bool one.
Now I got that those two are different.

But I still don't actually get what the difference is between Prop and bool.

**Comment by jeehoonkang** [comment]
Hi @sophiechoi 
- Both `Prop` and `bool` represent the type of truth values: true and false. `true:bool`, `false:bool`, `True:Prop`, and `False:Prop`. However, they differ in several respects.
- `bool` represents the type of truth expressions that can be evaluated to either `true` or `false`. For example, `evenb n` in the assignment is either `true` or `false`, regardless of the complexity of `n`. On the other hand, terms of `Prop` does not enjoy this property. A proposition `P:Prop` can be neither `True` nor `False`.
- However, `Prop` is more flexible in representing truth values than `bool`. For example, you can define less-than relation over natural numbers as follows: `Definition le n m : Prop := exists k, n + k = m`. However, you cannot define this in `bool`, as `exists k, n + k = m` is not bool (since you cannot compute the existential variable `k`). In this respect, you can express more ideas in `Prop` than `bool`.
- Thus those two types are complementary; `bool` enjoys a good property, while `Prop` is more flexible.

I think this explanation may be too abstract, or not to the point. It would be great if you explain me a little bit more of your difficulties (concrete examples, etc).

Jeehoon

**Comment by sophiechoi** [comment]
Thank you for great advice!

Aspect of computable(evaluable), I somehow got what Bool differs.
If I encounter some confusing examples of Prop, I'll ask again.

Thank you :)
