### ISSUE TITLE
About 'generalize dependent' tactic

### ISSUE THREAD

**Issue by minitu** [snu-sf/pl2015#58]
I've been using `generalize independent` tactic in some of the problems as I was told to do so.
But I don't think I have a full understanding of this tactic,
and it would be very helpful if you could explain why and when I should use it.
Thank you!

**Comment by jeehoonkang** [comment]
I am afraid I don't know the tactic `generalize independent`: https://www.google.co.kr/search?client=safari&rls=en&q=coq+%22generalize+independent%22&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=NxklVfb9KfT98wf1_oGYBw

Did you mean `generalize dependent`?

**Comment by minitu** [comment]
@jeehoonkang oops yes I meant `generalize dependent`...
I'll change the issue title.

**Comment by jeehoonkang** [comment]
It will be greatly helpful if you give me some example you encountered that `generalize dependent` is essential!

**Comment by minitu** [comment]
Well there were several in Assignment 4...
I had to use it in `double_induction`, for example.
When I didn't, I got stuck in one of the induction cases (I believe it was the last).

**Comment by jeehoonkang** [comment]
When you do induction over `n`, for example, the goal should be something like: `forall m, P(n, m)`. However, if `m` is in the context (above the `========` line; not in the goal below `========` as in `forall m, ...`), you have to move `m` in the context to the goal. The purpose of `generalize dependent` is that: moving a variable (in the example, `m`) from the context to the goal.

**Comment by jaewooklee93** [comment]
Well, you can use `generalize dependent` in `double_induction`, but you don't need it actually. Let me clarify it in detail.

First, you can consider the predicate `P` as a 2-dimensional infinite array of propositions.
![image](https://cloud.githubusercontent.com/assets/11328376/7061665/e2cdcdc4-decf-11e4-85bf-9f7ce19c91e1.png)
And then, the following is a graphical representation of the proof of `double_induction`.
![image](https://cloud.githubusercontent.com/assets/11328376/7061680/ff2ac120-decf-11e4-9fe6-df67e156e1f3.png)
If you `intros P H00 Hm0 H0n Hmn.`, your goal becomes `forall m n, P m n.`. I colored your goal with yellow.
![image](https://cloud.githubusercontent.com/assets/11328376/7061741/6d1a5182-ded0-11e4-910f-10457c8ab473.png)
At this point, you may want to `intros m.` as well. What `intros m.` does is fixing the value of `m`, so that you will be to prove `P` for each `m`, separately. Thus, `intros m.` makes yellow region smaller.
![image](https://cloud.githubusercontent.com/assets/11328376/7061764/ab92fb44-ded0-11e4-8bda-ef862f3e4c80.png)
Now, you have to use `induction m.`, BEFORE using `intros n.`. The tactic `induction` do the induction over inductively-defined set like `nat`. Your previous goal will be transformed into two subgoals, namely base case and inductive step.
![image](https://cloud.githubusercontent.com/assets/11328376/7061786/11a3cea4-ded1-11e4-9d7c-6e4700ea2a53.png)
Here I use blue color to indicate assumptions you can use as your induction hypothesis. The base case is trivial, while it also needs another induction over `n`. Let's assume we've already done the base case and think about inductive step.
You will use `intros n` for inductive step, of course that fixes the value of `n` and yellow region becomes even smaller and it is actually a single cell. Also, you have to `destruct n.` here, because the proof of `P(m,0)` and `P(m,S n')` are different. The latter one `P(m,S n')` is like.
![image](https://cloud.githubusercontent.com/assets/11328376/7061845/b3f0056a-ded1-11e4-8a4c-c6114689209f.png)
Now if you `apply Hmn` here, the goal will be solved. `Hmn` acts like the black arrow in the figure.

However, if you `intros m n.` and then `induction m.`, the story will be changed. `intros m n.` fixes the value of `m`, `n` like below.
![image](https://cloud.githubusercontent.com/assets/11328376/7061935/f374d7c8-ded2-11e4-9d14-0ada5e31c8e8.png)
And then `induction m` create the following two cases.
![image](https://cloud.githubusercontent.com/assets/11328376/7061948/1dc67982-ded3-11e4-85d7-580773e5fc20.png)
However, you may be aware that you cannot prove the inductive step, because you have very small induction hypothesis (blue region) this time. You cannot derive P(m+1,n) from P(m,n), i.e., you can use black arrows above, but you cannot use red arrow, and that's why you cannot prove in this time.

I hope that now you understand the order of `intros n` and `induction m` really matters, because if you use `induction m` after `intros n`, you will get smaller blue regions, so you become unable to prove your goal. In general, it's better to use `induction m` before `intros n` to get a stronger induction hypothesis. Therefore, in some case, you may want to revert or cancel the effect of  `intros n.`, and that's exactly what `generalize dependent n.` does. 

But, in this exercise `double_induction`, you don't have to use `generalize dependent n.`, because it's just OK if you use only `intros m.` and do `induction m.` before `intros n.`.

However, there are some cases you must use `generalize dependent`. For example, suppose that you have the following goal, `forall (n:nat) (l:list nat), P n l` and you want to do induction on `l`.  If you `intros n l.` first and then `induction l`, it will cause small blue region as above, because `n` is fixed by `intros`. You may want to try to type `intros l.` only, but it doesn't make desirable result, because Coq just CONVERTS the name of `(n:nat)` into `(l:nat)`, not `intros` `(l:list nat)`! Thus, in this case, your only choice is `intros n l.` and then `generalize dependent n.` followed by `induction l`.

I hope that this explanation helps your understanding.

**Comment by minitu** [comment]
@jeehoonkang @jaewooklee93 Thank you both for such a thorough explanation. I think I now have a much better understanding of how I should construct my proof.
