### ISSUE TITLE
Need to use 'ex_falso_quodlibet'

### ISSUE THREAD

**Issue by minitu** [snu-sf/pl2015#61]
I believe we need to use `apply ex_falso_quodlibet` in problem 12 of assignment 5,
to change `true = false` to `False` in the goal so that the hypothesis can be applied.
However, it says that the reference was not found. I think we should be able to use this.

**Comment by jaewooklee93** [comment]
If you have such an impossible goal like `true = false`, you may also have false assumption `H` in your context. Then `inversion H` will simply clear your goal. You may need other `assert` or `apply` tactics to convert `H` into `False`.

I strongly believe that if you are successful in solving the problem with `ex_falso_quodlibet`, you can also solve it without using that theorem, because `ex_falso_quodlibet` is nothing special or magical but just a natural feature induced from the structure of Coq itself.

**Comment by jeehoonkang** [comment]
I totally agree with @jaewooklee93 .

Jeehoon
