### ISSUE TITLE
Adding lemmas to assignment05_00

### ISSUE THREAD

**Issue by AdamBJ** [snu-sf/pl2015#66]
Can we add our own lemmas to assignment05_00? I want to add ex_false_quodlibet to it so that I don't have to copy/paste the defintion into each of the assignment files that I want to use it in.

**Comment by ik1ne** [comment]
https://github.com/snu-sf/pl2015/issues/64
It seems you can define lemmas everywhere you want!

**Comment by jaewooklee93** [comment]
However, bringing `ex_falso_quodlibet` from the past work is not a good idea, because it is much more convenient to use `inversion` tactic instead.

Please refer to #61 for details.

**Comment by alkaza** [comment]
will using the theorem be penalized?

**Comment by jeehoonkang** [comment]
- @ik1ne The question is: is it ok to use lemmas in `05_00`. On the other hand, the issue #64 asks if you can prove more lemmas in `05_32`, for example. The two are different questions.
- I would like you not to edit the `05_00` file.
- As @jaewooklee93 pointed out, you can use `inversion H` instead of applying `ex_false_quodlibet`.
- @alkaza However, you can prove and use `ex_falso_quodlibet` in, for example, `05_32.v`.

Jeehoon

**Comment by alkaza** [comment]
I apologize for asking again, I got confused in what is ok to do and what
is not.
1) Can I add previously proven theorems from the Logic.v file to
Assignment05_05?
2) Can I use Theorem ex_false_quodlibet in Assignment05_12?

**Comment by jeehoonkang** [comment]
@alkaza
- Yes you can add.
- You you can use, once you prove the theorem in `Assignment05_12.v`.

For more details on grading, please read my first reply in issue #60.

Jeehoon

**Comment by jeehoonkang** [comment]
Basically, if you succeeded in grading via the provided grader, it is OK. I will give you graders for every assignments from now on.

Jeehoon
